name = "dmc-navigator"
compatibility_date = "2026-02-27"
compatibility_flags = ["nodejs_compat"]

main = ".open-next/worker.mjs"

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "dmc_navigator_db"
database_id = "3a6ec73d-92bf-4197-9e5e-7a50ca29d53c"
